/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_testalu_out;
  wire [8-1:0] M_testalu_io_seg;
  wire [4-1:0] M_testalu_io_sel;
  alu_2 testalu (
    .clk(clk),
    .rst(rst),
    .a(io_dip[0+7-:8]),
    .b(io_dip[8+7-:8]),
    .alufn(io_dip[16+0+5-:6]),
    .out(M_testalu_out),
    .io_seg(M_testalu_io_seg),
    .io_sel(M_testalu_io_sel)
  );
  wire [8-1:0] M_my_testcase_aout;
  wire [8-1:0] M_my_testcase_bout;
  wire [8-1:0] M_my_testcase_out;
  wire [6-1:0] M_my_testcase_alufn;
  wire [8-1:0] M_my_testcase_io_seg;
  wire [4-1:0] M_my_testcase_io_sel;
  testcase_3 my_testcase (
    .clk(clk),
    .rst(rst),
    .io_button(io_button),
    .aout(M_my_testcase_aout),
    .bout(M_my_testcase_bout),
    .out(M_my_testcase_out),
    .alufn(M_my_testcase_alufn),
    .io_seg(M_my_testcase_io_seg),
    .io_sel(M_my_testcase_io_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    if (io_dip[16+7+0-:1] == 1'h1) begin
      io_led[16+7-:8] = M_my_testcase_out;
      io_led[8+7-:8] = M_my_testcase_bout;
      io_led[0+7-:8] = M_my_testcase_aout;
      io_seg = M_my_testcase_io_seg;
      io_sel = M_my_testcase_io_sel;
    end else begin
      io_led[16+7-:8] = M_testalu_out;
      io_led[8+7-:8] = io_dip[8+7-:8];
      io_led[0+7-:8] = io_dip[0+7-:8];
      io_seg = M_testalu_io_seg;
      io_sel = M_testalu_io_sel;
    end
  end
endmodule
